---
title: "Reproducible example (algebra problem)"
format: html
editor: visual
---

# Reproducible example attempt

We didn't get very far because of other interesting issues detailed in the word doc

-   we did try to do it from scratch but it was messing up weirdly so we started from the full doc and slowly removed stuff until it stopped working

```{r}
#| echo: false
library(data.table)
library(brms)
library(tidyverse)
```

```{r}
#| echo: false
set.seed(999)
location_parameter <- 0.91
scale_parameter <- 0.2
lapse <- 0.03

num_subj <- 4

#generate fake data
fakedata2 <- tidyr::expand_grid(
    speed = seq(.02,1.8, length.out = 12), #changed min and max speed to match our data
    subj = seq(1, num_subj),
    num_target = c(1,2,3),
    obj_per_ring = c(5,10), #two conditions for object density
    rep = seq(1,5) #5 replicants of each trial combination
  )


fakedata2 <- fakedata2 %>%
  mutate(
    chanceRate = 1/obj_per_ring,
    phi = pnorm(-speed, -location_parameter, scale_parameter),
    probabilityCorrect = chanceRate + (1-chanceRate - lapse*(1-chanceRate))*phi
  )

fakedata2 <- fakedata2 %>% mutate(
          correct = rbinom(n=length(probabilityCorrect), size = 1, prob = probabilityCorrect)
         )
          
```

## Plot our fake data

```{r}
#| echo: false
ggplot(fakedata2, aes(x=speed,y=correct)) + 
  stat_summary( fun="mean", geom="point" ) +
  facet_wrap(.~subj)

ggplot(fakedata2, aes(x=speed,y=correct)) + 
  stat_summary(fun="mean", geom="point" ) +
  facet_wrap(.~chanceRate) +
  aes(color = chanceRate)
```

```{r}
#| echo: false
model_formula <- bf(
  correct ~ chanceRate + (1-chanceRate - lapse*(1-chanceRate))*Phi(-(speed-eta)/exp(logsigma)), #this works
  eta ~ 1,
  lapse ~ 1,
  logsigma ~ 1,
  family = bernoulli(link="identity"), #because otherwise default link logit would be used
  nl = TRUE
)

p3 <- c(
  set_prior("beta(2,33.33)", class = "b", nlpar = "lapse", lb = 0, ub = 1),
  set_prior("uniform(0, 3)", class = "b", nlpar = "eta", lb = 0, ub = 3) #conservative ub of 3 rps
)
```

```{r}
#| echo: false

fit <- brm(
  model_formula,
  data = fakedata2,
  prior = p3
)

summary(fit)
```
