---
title: "dataWrangling"
format: html
editor: visual
---

```{r warning = 'false'}
library(tidyverse)
library(here)
```

```{r}
#Our data

```

```{r}
# Load the data
rf_data_raw <- read_csv(here("data", "roudaia_faubert_data", "dat_csvs", "sub-ALL_task-motc.csv"))

# naniar::gg_miss_var(rf_data_raw) ## no missing data

# glimpse(rf_data_raw) ## initial data analysis

rf_data_clean <- rf_data_raw %>%
  separate(# cond is in a format that includes both targets and rings so i seperate this
    cond, into = c("num_target", "obj_per_ring"), sep = "\\."
  ) %>%
  mutate(# make the newly created columns into numbers and remove characters
    num_target = as.numeric(str_replace_all(num_target, "[^0-9]", "")),
    obj_per_ring = as.numeric(str_replace_all(obj_per_ring, "[^0-9]", ""))
  ) %>%
  mutate(# convert the char columns to factor (categorical)
    subj = as_factor(subj), #participant
    group = as_factor(group), #young vs old
    gender = as_factor(gender), #M, F
    responseRing = as_factor(responseRing), #ring prompted
  ) %>%
  mutate(# recode for more common sense names (or to align with our data in future)
    group = fct_recode(group,
                       "younger" = "1",
                       "older" = "2"),
    responseRing = fct_recode(responseRing,
                             "inner" = "1",
                             "middle" = "2",
                             "outer" = "3"),
  )
  

glimpse(rf_data_clean)
```
